version: '3'

services:
  nodeserver:
    image: nodeserver
    environment:
      - $POSTGRES_USER
      - $POSTGRES_PASSWORD
      - $POSTGRES_DB
      - $POSTGRES_HOST
      - $POSTGRES_PORT
    build:
      context: .
      dockerfile: docker/node.dockerfile
    depends_on:
      - db
    ports:
      - 9229:9229
      - ${SERVER_PORT}:${SERVER_PORT}
    expose:
      - ${SERVER_PORT}
      - 9229
    volumes:
      - .:/var/www/nodeserver
    env_file:
      - .env
  db:
    image: postgres:13
    environment:
      - $POSTGRES_USER
      - $POSTGRES_PASSWORD
      - $POSTGRES_DB
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    expose:
      - 5432
    env_file:
      - .env
