version: '3'

services:
  nodeserver:
    image: nodeserver
    environment:
      - $POSTGRES_USER
      - $POSTGRES_PASSWORD
      - $POSTGRES_DB
      - $POSTGRES_HOST
      - $POSTGRES_PORT
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}

    depends_on:
      - db
    ports:
      - 9229:9229
      - ${PORT}:${PORT}
    expose:
      - ${PORT}
      - 9229
    volumes:
      - .:/var/www/nodeserver
      - /app/node_modules/

    env_file:
      - .env
  db:
    image: postgres:13
    environment:
      - $POSTGRES_USER
      - $POSTGRES_PASSWORD
      - $POSTGRES_DB
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    expose:
      - 5432
    env_file:
      - .env
